<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>MicroFramework</title>
    <link rel="stylesheet" href="/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="/css/index.css">
    <script src="/js/jquery-2.1.4.min.js"></script>
    <script src="/js/bootstrap.min.js"></script>
</head>

<body>
<?php include ('layout/menu.phtml'); ?>

<div class="container">


    <div class="starter-template">
        <h1>CONTROLLER TEMPLATE</h1>
        <?php echo \core\Application::render(); ?>
    </div>

</div>
</body>

</html>