<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">MicroFramework</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li <?php echo (core\Router::getInstance()->isCurrentRoute('/home')) ? 'class="active"' : ''; ?>>
                    <a href="/">Home</a>
                </li>
                <li <?php echo (core\Router::getInstance()->isCurrentRoute('/library')) ? 'class="active"' : ''; ?>>
                    <a href="/library">Library</a>
                </li>
                <li <?php echo (core\Router::getInstance()->isCurrentRoute('/config')) ? 'class="active"' : ''; ?>>
                    <a href="/config">Config</a>
                </li>
            </ul>
        </div>
    </div>
</nav>