<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>MicroFramework</title>
    <?php
    echo \core\Layout::appendCss(array(
        '/css/bootstrap.min.css',
        '/css/bootstrap-theme.min.css',
        '/css/index.css'
    ))->outputStylesheet();

    echo \core\Layout::appendJs(array(
        '/js/jquery-2.1.4.min.js',
        '/js/bootstrap.min.js'
    ))->outputJavascript();
    ?>
</head>

<body>

<?php include('layout/menu.phtml'); ?>

<div class="container">
    <h1>MODULE TEMPLATE</h1>
    <?php echo \core\Application::render(); ?>
</div>
</body>

</html>