<form class="form-horizontal">
    <fieldset>
        <legend>Connection</legend>
        <div class="form-group">
            <label class="col-md-4 control-label" for="host">Host</label>

            <div class="col-md-4">
                <input type="text" name="host" id="host" value="">
            </div>

        </div>
        <div class="form-group">
            <label class="col-md-4 control-label" for="login">Login</label>

            <div class="col-md-4">
                <input type="text" name="pass" id="login" value=""></div>
        </div>
        <div class="form-group">
            <label class="col-md-4 control-label" for="pass">Password</label>

            <div class="col-md-4">
                <input type="password" name="pass" id="pass" value=""></div>
        </div>
        <div class="form-group">
            <div class="col-md-4"></div>
            <div class="col-md-4">
                <input type="submit" class="btn btn-primary" value="Submit"></div>
        </div>
    </fieldset>
</form>